name: Deploy to GitHub Pages

# Запускаем скрипт при каждом обновлении основной ветки (main)
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    # Используем стандартный сервер для сборки
    runs-on: ubuntu-latest
    steps:
      # 1. Копируем код вашего репозитория на сервер
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      # 2. Главный шаг: Внедрение секрета
      - name: Replace API Key in HTML 🤫
        run: |
          # Эта команда находит в вашем HTML файле метку %%GEMINI_API_KEY%%
          # и заменяет ее на реальный ключ, который вы добавили в секреты.
          # ВНИМАНИЕ: Если ваш HTML-файл называется иначе, измените имя в строке ниже.
          awk -v key="${{ secrets.GEMINI_API_KEY }}" '{gsub("%%GEMINI_API_KEY%%", key)}1' tool_rental_business_simulator_v6.html > index.html

      # 3. Шаг для самопроверки (вы сможете посмотреть результат в логах)
      - name: Verify Key Replacement (DEBUG) ✅
        run: |
          echo "Проверяем, был ли ключ вставлен в index.html:"
          # Ищем строку с ключом и выводим в лог ее начало и конец для проверки.
          grep 'const apiKey =' index.html | awk -F'"' '{print $1 "\"" substr($2, 1, 4) "..." substr($2, length($2)-3) "\""}'
      
      # 4. Публикация готового сайта на GitHub Pages
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # Публикуем в специальную ветку gh-pages
          folder: .       # Публикуем все содержимое папки

