name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1. Копируем код репозитория
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      # 2. Внедряем секрет прямо в index.html
      - name: Replace API Key in index.html 🤫
        run: |
          # Эта команда работает напрямую с вашим главным файлом index.html
          sed -i 's|%%GEMINI_API_KEY%%|${{ secrets.GEMINI_API_KEY }}|g' index.html
        
      # 3. Публикуем результат
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
          clean: true # Эта опция удалит все старые файлы из ветки публикации

